package Commands;

import Exceptions.ContainerNotFoundException;
import Exceptions.Ship.*;
import Exceptions.WarehouseItemNotFoundException;
import Exceptions.WarehouseNotFoundException;
import Exceptions.WarehouseStorageCapacityExceededException;

public interface ICommand {

    void execute() throws HazardousContainerStorageExceededException, ContainerStorageWeightExceededException, WarehouseItemNotFoundException, ContainerStorageCapacityExceededException, ElectrifiedContainerStorageExceededException, HeavyContainerStorageExceededException, WarehouseNotFoundException, ContainerNotFoundException, WarehouseStorageCapacityExceededException;
}
